// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTourGenius.Models;

namespace TempleTourGenius.Migrations
{
    [DbContext(typeof(SignupDBContext))]
    [Migration("20220322041355_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("TempleTourGenius.Models.Timeslots", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.HasKey("Time");

                    b.ToTable("Timeslots");

                    b.HasData(
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 21, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 22, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 23, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 24, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 25, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 26, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 8, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 9, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 10, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 11, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 12, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 13, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 14, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 15, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 16, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 17, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 18, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 19, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        },
                        new
                        {
                            Time = new DateTime(2022, 3, 27, 20, 0, 0, 0, DateTimeKind.Local),
                            Available = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
